### ISSUE TITLE
Ensure Consistent Case Formatting for "Large" and "Medium" Size Options

### ISSUE THREAD

**Issue by ThakshilaJay** [akilawijesinghe/TRBAS#61]
![image](https://github.com/user-attachments/assets/3dacdceb-7931-4344-b7b1-40fb4eb1cf97)
Currently, the size options displayed on the UI have inconsistent case formatting. The word "Large" is capitalized, while "MEDIUM" appears in uppercase. To maintain uniformity and improve user experience, all size options should follow the same formatting, either all capitalized or all uppercase

**Comment by akilawijesinghe** [comment]
The size input field is a free-text field, allowing admins to input billboard sizes in various formats, such as 'medium', 'large', or in specific units like inches, meters, or centimeters. This flexibility ensures admins can freely type and describe the size in a way that best suits their needs.
